---
title: "P8105_hw6_jjam2530"
author: "Jenna Mohammed"
date: '2023-11-28'
output: github_document
---

```{r}
library(readr)
library(tidyverse)
library(modelr)
library(p8105.datasets)
```

# Problem 1
```{r}
urlfile = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

data <- read_csv(url(urlfile))
```

# Problem 2 

Loading in the data for problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

view(weather_df)
```

fitting a regression model 

```{r}
fit <- lm(tmax ~ tmin + prcp, data = weather_df) |>
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

Creating function for bootstrap

```{r}
boot_sample = function(weather_df) {
  sample_frac(weather_df, replace = TRUE)
}
```

Estimate for r hat squared 

```{r}
r_squared = 
  weather_df |>
  bootstrap(n = 5000) |>
  mutate(
    models = map(.x = strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) |>
  unnest(results)

r_squared %>% 
  ggplot(aes(x = r.squared)) + 
  geom_density()

```

Estimate for log(beta_0 * beta_1)

```{r}
log_var =
  weather_df |>
  bootstrap(n = 5000) |>
  mutate(
    models = map(.x = strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) |>
  select(strap_number, term, estimate) |>
  unnest(results) |>
  mutate(
    log_function = log(`(Intercept)`*tmin)
  ) 

log_var|> 
  ggplot(aes(x = log_function)) + 
  geom_density()

```



###### IGNORE #########

stating the number of bootstrap samples 

```{r}
 boot_number <- 5000
```



function to generate bootstrap samples

```{r}


boot_function = function(weather_df) {
  sample_frac(weather_df, replace = TRUE)
  fit <- lm(tmax ~ tmin + prcp, data = weather_df)
  return(summary(model)[["r.squared"]])
}


num_samples <- 5000




weather_bootstrap1 = 
  weather_df %>% 
  modelr::bootstrap(n = 5000, id = "strap_number") %>% 
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(strap_number, results) %>% 
  unnest(results) 
weather_bootstrap1

```

```{r}
boot_sample(weather_df) |> 
  ggplot(aes(x = tmin, y = prcp)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```



